# Generated by Django 6.1 on 2026-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
