# Generated by Django 6.1 on 2026-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
