# Generated by Django 6.1 on 2026-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_message_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='images/comments'),
        ),
    ]
